<?php

namespace AppBundle\Repository;

/**
 * PaypalPaymentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaypalPaymentsRepository extends \Doctrine\ORM\EntityRepository
{
}
