<?php

namespace AppBundle\Repository;

/**
 * TokensRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TokensRepository extends \Doctrine\ORM\EntityRepository
{
}
